definitions:
  core.NotificationMsg:
    properties:
      content:
        description: Content of the template
        example: A new event has been received.
        type: string
      recipient:
        description: Recipient of the notification if type is email
        example: info@email.com
        type: string
      subject:
        description: Subject of the notification
        example: New Notification
        type: string
      type:
        description: Type of the notification (e.g. email, snow, etc.)
        example: email
        type: string
    type: object
info:
  contact:
    email: info@southwinds.io
    name: SouthWinds Tech ltd
    url: https://www.southwinds.io/
  description: Notification Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Notify Service
  version: 1.0.0
paths:
  /:
    get:
      description: |-
        Checks that the HTTP server is listening on the required port.
        Use a liveliness probe.
        It does not guarantee the server is ready to accept calls.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check that the HTTP API is live
      tags:
      - General
  /notify:
    post:
      consumes:
      - application/yaml
      - ' application/json'
      description: sends a notification of the specified type
      parameters:
      - description: the notification information to send
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/core.NotificationMsg'
      produces:
      - text/plain
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sends a new notification
      tags:
      - Notifications
swagger: "2.0"
